spring:
  application:
    name: api-gateway

  main:
    web-application-type: reactive

  cloud:
    gateway:
      server:
        webflux:

          discovery:
            locator:
              enabled: false
              lower-case-service-id: true

          routes:

            - id: auth-service
              uri: lb://auth-service
              predicates:
                - Path=/api/auth/**

            - id: product-service
              uri: lb://product-service
              predicates:
                - Path=/api/products/**

            - id: cart-service
              uri: lb://cart-service
              predicates:
                - Path=/api/cart/**

            - id: order-service
              uri: lb://order-service
              predicates:
                - Path=/api/orders/**

            - id: inventory-service
              uri: lb://inventory-service
              predicates:
                - Path=/api/inventory/**

            - id: payment-service
              uri: lb://payment-service
              predicates:
                - Path=/api/payments/**

            - id: notification-service
              uri: lb://notification-service
              predicates:
                - Path=/api/notifications/**

eureka:
  client:
    service-url:
      defaultZone: http://ecommerce-eureka-server:8761/eureka/

management:
  endpoint:
    gateway:
      access: read-only

  endpoints:
    web:
      exposure:
        include: health,info,gateway