spring:
  application:
    name: api-gateway

  main:
    web-application-type: reactive

  config:
    import: "${SPRING_CONFIG_IMPORT:configserver:http://localhost:8888}"

management:
  endpoint:
    gateway:
      access: read-only

  endpoints:
    web:
      exposure:
        include: health,info,gateway